#!/usr/local/bin/python3
# encoding: utf-8

domains = ["blocksworld","gripper","miconic","satellite","rovers","termes"]
drifted_domain_file = "domain.pddl" # IPC domain
regenerate_random_states = False

# Computed automatically in generate_random_init_domains.py and learn_model.py
domain_to_total_pals, domain_to_total_pals_increased_applicability = dict(), dict()

# Type of init domains to be generated. Each init_domain_file has filename format: domainname_#PALsAffected_#file.pddl
flag_init_domains_type_dict = {0: "randomly generated init domains", 1: "only increased applicability init domains", 2: "both types of domain generation"}   
flag_init_domains_type = 0  # 0 for randomly generated init domains
flag_approach = 2           # always set to 2 as the approach does not know the type (increased/reduced fucntionality) of the domains

# Number of init domains generated for each #PALsAffected being considered
domain_to_num_files_each_pal = {"blocksworld":6,"gripper":6,"miconic":6,"satellite":6,"rovers":6,"termes":2}
num_affected_pals = 20     # total_pals/num_pals decides the interval between the #PALsAffected for init domains
domains_mix_intervals = {'blocksworld': 2, 'gripper':1, 'miconic':1, 'satellite': 2, 'rovers':4, 'parking':2, 'termes':10, 'freecell':50, 'logistics':10}

# Number of observations (i.e. s-a-s) used (should always be <= the number of obs in the plan generated by the input instance)
# Delete intermediate instances and observation files if you change the init_domains for any flag_init_domains_type
domain_to_num_sas = {'blocksworld': 10, 'gripper':10, 'miconic':10, 'satellite': 10, 'rovers':10, 'termes':10} 
