(define (domain Rover)
    (:requirements :typing)
    (:types rover waypoint store camera mode lander objective)
    
    (:predicates (at ?x - rover ?y - waypoint) 
                 (at_lander ?x - lander ?y - waypoint)
                 (can_traverse ?r - rover ?x - waypoint ?y - waypoint)
                 (equipped_for_soil_analysis ?r - rover)
                 (equipped_for_rock_analysis ?r - rover)
                 (equipped_for_imaging ?r - rover)
                 (empty ?s - store)
                 (have_rock_analysis ?r - rover ?w - waypoint)
                 (have_soil_analysis ?r - rover ?w - waypoint)
                 (full ?s - store)
                 (calibrated ?c - camera ?r - rover) 
                 (supports ?c - camera ?m - mode)
                 (available ?r - rover)
                 (visible ?w - waypoint ?p - waypoint)
                 (have_image ?r - rover ?o - objective ?m - mode)
                 (communicated_soil_data ?w - waypoint)
                 (communicated_rock_data ?w - waypoint)
                 (communicated_image_data ?o - objective ?m - mode)
                 (at_soil_sample ?w - waypoint)
                 (at_rock_sample ?w - waypoint)
                 (visible_from ?o - objective ?w - waypoint)
                 (store_of ?s - store ?r - rover)
                 (calibration_target ?i - camera ?o - objective)
                 (on_board ?i - camera ?r - rover)
                 (channel_free ?l - lander)
    )
    
    (:action navigate
        :parameters (?x - rover 
                     ?y - waypoint 
                     ?z - waypoint) 
        :precondition (and 
               (have_rock_analysis ?x ?z)
			(visible ?z ?y)
			(not (equipped_for_imaging ?x))
			(not (at_rock_sample ?y))
			(can_traverse ?x ?z ?y)
			(at_soil_sample ?z)
			(not (at_soil_sample ?y))
			(not (communicated_soil_data ?z))
			(communicated_rock_data ?z)
			(not (communicated_soil_data ?y))
			(not (equipped_for_rock_analysis ?x))
			(not (at ?x ?z))
			(not (have_soil_analysis ?x ?z))
			(not (communicated_rock_data ?y))
			(not (equipped_for_soil_analysis ?x))
			
          )
          :effect (and 
               (available ?x)
			(not (visible ?z ?y))
			(equipped_for_imaging ?x)
			(at_rock_sample ?y)
			(can_traverse ?x ?z ?y)
			(not (have_soil_analysis ?x ?y))
			(not (at_soil_sample ?z))
			(not (communicated_soil_data ?z))
			(communicated_rock_data ?z)
			(not (communicated_soil_data ?y))
			(visible ?y ?z)
			(not (equipped_for_rock_analysis ?x))
			(not (can_traverse ?x ?y ?z))
			(not (at ?x ?z))
			(not (have_soil_analysis ?x ?z))
			(have_rock_analysis ?x ?y)
			(communicated_rock_data ?y)
			(not (equipped_for_soil_analysis ?x))
			
          )
    )
    
    (:action sample_soil
        :parameters (?x - rover ?s - store ?p - waypoint)
        :precondition (and 
               (not (available ?x))
			(not (at ?x ?p))
			(not (empty ?s))
			(full ?s)
			(store_of ?s ?x)
			(at_rock_sample ?p)
			(not (communicated_soil_data ?p))
			(have_soil_analysis ?x ?p)
			(not (communicated_rock_data ?p))
			(not (equipped_for_rock_analysis ?x))
			(not (have_rock_analysis ?x ?p))
			
          )
        :effect (and 
               (not (available ?x))
			(at ?x ?p)
			(not (equipped_for_imaging ?x))
			(store_of ?s ?x)
			(not (at_soil_sample ?p))
			(not (at_rock_sample ?p))
			(equipped_for_soil_analysis ?x)
			(not (communicated_soil_data ?p))
			(not (have_soil_analysis ?x ?p))
			(communicated_rock_data ?p)
			(not (equipped_for_rock_analysis ?x))
			(have_rock_analysis ?x ?p)
			
          )
    )
    
    (:action sample_rock
        :parameters (?x - rover 
                     ?s - store 
                     ?p - waypoint)
        :precondition (and 
               (not (available ?x))
			(not (at ?x ?p))
			(not (empty ?s))
			(equipped_for_imaging ?x)
			(not (full ?s))
			(at_soil_sample ?p)
			(not (at_rock_sample ?p))
			(not (equipped_for_soil_analysis ?x))
			(communicated_soil_data ?p)
			(have_soil_analysis ?x ?p)
			(not (communicated_rock_data ?p))
			(equipped_for_rock_analysis ?x)
			(have_rock_analysis ?x ?p)
			
          )
        :effect (and 
               (available ?x)
			(at ?x ?p)
			(not (full ?s))
			(not (at_soil_sample ?p))
			(equipped_for_soil_analysis ?x)
			(not (communicated_soil_data ?p))
			(not (have_soil_analysis ?x ?p))
			(have_rock_analysis ?x ?p)
			
          )
    )
    
    (:action drop
        :parameters (?x - rover 
                     ?y - store)
        :precondition (and 
               (available ?x)
			(not (store_of ?y ?x))
			(empty ?y)
			(not (equipped_for_rock_analysis ?x))
			(equipped_for_soil_analysis ?x)
			(not (full ?y))
			
          )
        :effect (and 
               (not (available ?x))
			(not (empty ?y))
			(not (equipped_for_rock_analysis ?x))
			(equipped_for_soil_analysis ?x)
			(full ?y)
			(not (equipped_for_imaging ?x))
			
          )
    )
    
    (:action calibrate
         :parameters (?r - rover 
                      ?i - camera 
                      ?t - objective 
                      ?w - waypoint)
         :precondition (and 
               (not (calibration_target ?i ?t))
			(equipped_for_rock_analysis ?r)
			(have_soil_analysis ?r ?w)
			(not (available ?r))
			(not (equipped_for_imaging ?r))
			(not (at ?r ?w))
			(at_rock_sample ?w)
			(equipped_for_soil_analysis ?r)
			(not (communicated_soil_data ?w))
			(communicated_rock_data ?w)
			(not (at_soil_sample ?w))
			(calibrated ?i ?r)
			
          )
         :effect (and 
               (not (calibration_target ?i ?t))
			(equipped_for_rock_analysis ?r)
			(have_soil_analysis ?r ?w)
			(not (available ?r))
			(at ?r ?w)
			(on_board ?i ?r)
			(not (at_rock_sample ?w))
			(not (equipped_for_soil_analysis ?r))
			(visible_from ?t ?w)
			(not (have_rock_analysis ?r ?w))
			(not (communicated_soil_data ?w))
			(not (communicated_rock_data ?w))
			(not (at_soil_sample ?w))
			(not (calibrated ?i ?r))
			
          )
    )  
    
    (:action take_image
         :parameters (?r - rover 
                      ?p - waypoint 
                      ?o - objective 
                      ?i - camera 
                      ?m - mode)
         :precondition (and 
               (not (supports ?i ?m))
			(communicated_image_data ?o ?m)
			(not (have_soil_analysis ?r ?p))
			(equipped_for_rock_analysis ?r)
			(have_image ?r ?o ?m)
			(not (calibration_target ?i ?o))
			(not (equipped_for_soil_analysis ?r))
			(not (on_board ?i ?r))
			(at_rock_sample ?p)
			(not (communicated_soil_data ?p))
			(communicated_rock_data ?p)
			(not (calibrated ?i ?r))
			(at ?r ?p)
			
          )
          :effect (and 
               (not (supports ?i ?m))
			(not (communicated_image_data ?o ?m))
			(have_soil_analysis ?r ?p)
			(not (calibration_target ?i ?o))
			(not (equipped_for_soil_analysis ?r))
			(not (equipped_for_imaging ?r))
			(on_board ?i ?r)
			(not (at_rock_sample ?p))
			(visible_from ?o ?p)
			(not (communicated_soil_data ?p))
			(not (communicated_rock_data ?p))
			(calibrated ?i ?r)
			(not (at ?r ?p))
			
          )
    )
    
    (:action communicate_soil_data
         :parameters (?r - rover 
                      ?l - lander 
                      ?p - waypoint 
                      ?x - waypoint 
                      ?y - waypoint)
         :precondition (and 
               (not (equipped_for_imaging ?r))
			(visible ?y ?x)
			(not (have_soil_analysis ?r ?x))
			(communicated_rock_data ?x)
			(visible ?p ?y)
			(not (visible ?x ?y))
			(at_rock_sample ?x)
			(can_traverse ?r ?p ?y)
			(not (at ?r ?p))
			(have_soil_analysis ?r ?y)
			(not (at ?r ?y))
			(can_traverse ?r ?x ?y)
			(not (have_soil_analysis ?r ?p))
			(not (at_rock_sample ?y))
			(at_soil_sample ?p)
			(at_rock_sample ?p)
			(not (at ?r ?x))
			(not (communicated_rock_data ?p))
			(at_lander ?l ?y)
			(not (have_rock_analysis ?r ?y))
			(not (equipped_for_soil_analysis ?r))
			(not (at_soil_sample ?y))
			(communicated_soil_data ?x)
			(at_soil_sample ?x)
			(communicated_soil_data ?y)
			(not (can_traverse ?r ?x ?p))
			(have_rock_analysis ?r ?x)
			(at_lander ?l ?p)
			(not (communicated_soil_data ?p))
			(visible ?x ?p)
			(visible ?y ?p)
			(communicated_rock_data ?y)
			(not (can_traverse ?r ?p ?x))
			
          )
          :effect (and 
               (channel_free ?l)
			(not (equipped_for_imaging ?r))
			(not (visible ?y ?x))
			(have_soil_analysis ?r ?x)
			(not (communicated_rock_data ?x))
			(not (visible ?x ?y))
			(not (at_rock_sample ?x))
			(can_traverse ?r ?p ?y)
			(not (at ?r ?p))
			(not (have_soil_analysis ?r ?y))
			(not (at ?r ?y))
			(not (have_soil_analysis ?r ?p))
			(not (available ?r))
			(not (at_rock_sample ?y))
			(not (at_soil_sample ?p))
			(at_rock_sample ?p)
			(at ?r ?x)
			(not (communicated_rock_data ?p))
			(not (can_traverse ?r ?y ?p))
			(at_lander ?l ?y)
			(at_lander ?l ?x)
			(not (equipped_for_soil_analysis ?r))
			(not (at_soil_sample ?y))
			(not (communicated_soil_data ?x))
			(not (at_soil_sample ?x))
			(not (have_rock_analysis ?r ?p))
			(not (communicated_soil_data ?y))
			(not (can_traverse ?r ?x ?p))
			(at_lander ?l ?p)
			(communicated_soil_data ?p)
			(equipped_for_rock_analysis ?r)
			(not (visible ?x ?p))
			(visible ?y ?p)
			(can_traverse ?r ?y ?x)
			
          )
    )
    
    (:action communicate_rock_data
         :parameters (?r - rover 
                      ?l - lander 
                      ?p - waypoint 
                      ?x - waypoint 
                      ?y - waypoint)
         :precondition (and 
               (not (channel_free ?l))
			(equipped_for_imaging ?r)
			(visible ?y ?x)
			(not (have_soil_analysis ?r ?x))
			(not (communicated_rock_data ?x))
			(not (visible ?p ?x))
			(not (visible ?p ?y))
			(not (at_rock_sample ?x))
			(not (can_traverse ?r ?p ?y))
			(not (at ?r ?p))
			(not (have_soil_analysis ?r ?y))
			(not (at ?r ?y))
			(not (can_traverse ?r ?x ?y))
			(have_soil_analysis ?r ?p)
			(not (at_rock_sample ?y))
			(not (at_soil_sample ?p))
			(at_rock_sample ?p)
			(not (at ?r ?x))
			(communicated_rock_data ?p)
			(can_traverse ?r ?y ?p)
			(not (equipped_for_soil_analysis ?r))
			(not (at_soil_sample ?y))
			(communicated_soil_data ?x)
			(communicated_soil_data ?y)
			(can_traverse ?r ?x ?p)
			(have_rock_analysis ?r ?x)
			(at_lander ?l ?p)
			(communicated_soil_data ?p)
			(equipped_for_rock_analysis ?r)
			(visible ?x ?p)
			(not (visible ?y ?p))
			(not (communicated_rock_data ?y))
			(can_traverse ?r ?p ?x)
			
          )
          :effect (and 
               (not (channel_free ?l))
			(equipped_for_imaging ?r)
			(not (have_soil_analysis ?r ?x))
			(not (communicated_rock_data ?x))
			(visible ?p ?x)
			(not (visible ?p ?y))
			(not (visible ?x ?y))
			(not (at_rock_sample ?x))
			(can_traverse ?r ?p ?y)
			(not (at ?r ?p))
			(not (have_soil_analysis ?r ?y))
			(not (at ?r ?y))
			(not (can_traverse ?r ?x ?y))
			(not (have_soil_analysis ?r ?p))
			(not (available ?r))
			(not (at_rock_sample ?y))
			(at_soil_sample ?p)
			(not (at_rock_sample ?p))
			(communicated_rock_data ?p)
			(can_traverse ?r ?y ?p)
			(at_lander ?l ?x)
			(have_rock_analysis ?r ?y)
			(not (equipped_for_soil_analysis ?r))
			(at_soil_sample ?y)
			(not (communicated_soil_data ?x))
			(not (at_soil_sample ?x))
			(communicated_soil_data ?y)
			(can_traverse ?r ?x ?p)
			(have_rock_analysis ?r ?x)
			(at_lander ?l ?p)
			(communicated_soil_data ?p)
			(equipped_for_rock_analysis ?r)
			(visible ?x ?p)
			(not (visible ?y ?p))
			(not (can_traverse ?r ?y ?x))
			(not (can_traverse ?r ?p ?x))
			
          )
    )
    
    (:action communicate_image_data
         :parameters (?r - rover 
                      ?l - lander 
                      ?o - objective 
                      ?m - mode 
                      ?x - waypoint 
                      ?y - waypoint)
         :precondition (and 
               (channel_free ?l)
			(equipped_for_imaging ?r)
			(visible ?y ?x)
			(not (have_image ?r ?o ?m))
			(not (have_soil_analysis ?r ?x))
			(not (visible ?x ?y))
			(not (at_rock_sample ?x))
			(have_soil_analysis ?r ?y)
			(not (at ?r ?y))
			(available ?r)
			(at_rock_sample ?y)
			(not (visible_from ?o ?x))
			(not (at ?r ?x))
			(equipped_for_soil_analysis ?r)
			(at_soil_sample ?y)
			(communicated_soil_data ?x)
			(not (at_soil_sample ?x))
			(communicated_soil_data ?y)
			(have_rock_analysis ?r ?x)
			(can_traverse ?r ?y ?x)
			(communicated_rock_data ?y)
			(communicated_image_data ?o ?m)
			
          )
         :effect (and 
               (not (channel_free ?l))
			(equipped_for_imaging ?r)
			(visible ?y ?x)
			(not (have_image ?r ?o ?m))
			(not (have_soil_analysis ?r ?x))
			(not (communicated_rock_data ?x))
			(visible ?x ?y)
			(not (at_rock_sample ?x))
			(have_soil_analysis ?r ?y)
			(not (at ?r ?y))
			(not (can_traverse ?r ?x ?y))
			(not (at_rock_sample ?y))
			(not (visible_from ?o ?x))
			(at ?r ?x)
			(at_lander ?l ?y)
			(at_lander ?l ?x)
			(not (have_rock_analysis ?r ?y))
			(equipped_for_soil_analysis ?r)
			(not (at_soil_sample ?y))
			(communicated_soil_data ?x)
			(at_soil_sample ?x)
			(not (communicated_soil_data ?y))
			(have_rock_analysis ?r ?x)
			(visible_from ?o ?y)
			(equipped_for_rock_analysis ?r)
			(not (can_traverse ?r ?y ?x))
			(not (communicated_rock_data ?y))
			(not (communicated_image_data ?o ?m))
			
          )
    )

)

;; 
;; navigate action has changed: (visible ?y ?z), (communicated_rock_data ?y), (communicated_soil_data ?z), (available ?x), (can_traverse ?x ?y ?z), (equipped_for_soil_analysis ?x), (at ?x ?y), (at_soil_sample ?y), (can_traverse ?x ?y ?z), (have_soil_analysis ?x ?z), (equipped_for_imaging ?x), (have_rock_analysis ?x ?y), (equipped_for_rock_analysis ?x), (equipped_for_rock_analysis ?x), (have_soil_analysis ?x ?z), (communicated_rock_data ?y), (equipped_for_imaging ?x), (have_soil_analysis ?x ?y), (communicated_soil_data ?y), (can_traverse ?x ?z ?y), (available ?x), (at ?x ?z), (at_soil_sample ?z), (at_rock_sample ?y), (visible ?z ?y), (at ?x ?y), (at_rock_sample ?y), (communicated_soil_data ?y), (visible ?y ?z), (at ?x ?z), (at_soil_sample ?z), (have_rock_analysis ?x ?z), (communicated_soil_data ?z), (communicated_rock_data ?z), (visible ?z ?y), (communicated_rock_data ?z), (equipped_for_soil_analysis ?x), (can_traverse ?x ?z ?y), 
;; take_image action has changed: (equipped_for_soil_analysis ?r), (communicated_rock_data ?p), (equipped_for_imaging ?r), (equipped_for_soil_analysis ?r), (visible_from ?o ?p), (have_image ?r ?o ?m), (at_rock_sample ?p), (communicated_image_data ?o ?m), (communicated_soil_data ?p), (communicated_soil_data ?p), (equipped_for_rock_analysis ?r), (at ?r ?p), (supports ?i ?m), (equipped_for_imaging ?r), (on_board ?i ?r), (communicated_rock_data ?p), (calibration_target ?i ?o), (visible_from ?o ?p), (communicated_image_data ?o ?m), (supports ?i ?m), (on_board ?i ?r), (calibrated ?i ?r), (have_soil_analysis ?r ?p), (calibrated ?i ?r), (calibration_target ?i ?o), (have_soil_analysis ?r ?p), (at_rock_sample ?p), (have_image ?r ?o ?m), 
;; communicate_soil_data action has changed: (visible ?y ?x), (communicated_soil_data ?x), (communicated_rock_data ?p), (at_lander ?l ?x), (communicated_rock_data ?x), (at_rock_sample ?x), (at ?r ?x), (have_soil_analysis ?r ?x), (at_lander ?l ?p), (have_rock_analysis ?r ?p), (visible ?x ?p), (at_rock_sample ?p), (can_traverse ?r ?p ?y), (at ?r ?p), (can_traverse ?r ?y ?p), (communicated_soil_data ?p), (at_soil_sample ?p), (visible ?x ?p), (have_rock_analysis ?r ?x), (visible ?y ?p), (visible ?y ?x), (can_traverse ?r ?x ?p), (visible ?p ?y), (have_soil_analysis ?r ?y), (channel_free ?l), (equipped_for_soil_analysis ?r), (at_soil_sample ?p), (visible ?x ?y), (can_traverse ?r ?x ?y), (have_soil_analysis ?r ?p), (can_traverse ?r ?y ?x), (at_soil_sample ?y), (at_rock_sample ?y), (can_traverse ?r ?p ?x), (equipped_for_imaging ?r), (at ?r ?p), (have_soil_analysis ?r ?x), (at_rock_sample ?y), (have_rock_analysis ?r ?y), (at_soil_sample ?x), (at_rock_sample ?x), (communicated_soil_data ?y), (visible ?x ?y), (equipped_for_rock_analysis ?r), (at_lander ?l ?y), (communicated_rock_data ?x), (can_traverse ?r ?p ?y), (have_soil_analysis ?r ?y), (communicated_soil_data ?x), (at_lander ?l ?p), (communicated_soil_data ?y), (have_soil_analysis ?r ?p), (at_rock_sample ?p), (available ?r), (at ?r ?y), (at ?r ?y), (communicated_rock_data ?y), (at_soil_sample ?x), (channel_free ?l), (available ?r), (at ?r ?x), (equipped_for_imaging ?r), (visible ?y ?p), (can_traverse ?r ?x ?p), (at_soil_sample ?y), (equipped_for_soil_analysis ?r), (communicated_rock_data ?p), 
;; calibrate action has changed: (at ?r ?w), (equipped_for_rock_analysis ?r), (on_board ?i ?r), (available ?r), (at_soil_sample ?w), (communicated_rock_data ?w), (at ?r ?w), (visible_from ?t ?w), (visible_from ?t ?w), (equipped_for_imaging ?r), (calibrated ?i ?r), (have_soil_analysis ?r ?w), (have_rock_analysis ?r ?w), (at_rock_sample ?w), (on_board ?i ?r), (calibrated ?i ?r), (equipped_for_rock_analysis ?r), (communicated_rock_data ?w), (calibration_target ?i ?t), (at_rock_sample ?w), (equipped_for_soil_analysis ?r), (calibration_target ?i ?t), (at_soil_sample ?w), (equipped_for_soil_analysis ?r), (communicated_soil_data ?w), (communicated_soil_data ?w), (have_soil_analysis ?r ?w), (available ?r), 
;; drop action has changed: (equipped_for_rock_analysis ?x), (available ?x), (empty ?y), (equipped_for_rock_analysis ?x), (full ?y), (equipped_for_soil_analysis ?x), (empty ?y), (equipped_for_soil_analysis ?x), (equipped_for_imaging ?x), (store_of ?y ?x), (full ?y), (available ?x), 
;; communicate_image_data action has changed: (have_soil_analysis ?r ?y), (at ?r ?y), (communicated_soil_data ?y), (at_lander ?l ?x), (visible ?x ?y), (at_lander ?l ?y), (communicated_image_data ?o ?m), (at_soil_sample ?x), (communicated_soil_data ?x), (at_lander ?l ?y), (equipped_for_rock_analysis ?r), (have_soil_analysis ?r ?y), (channel_free ?l), (at_soil_sample ?y), (communicated_rock_data ?y), (visible ?y ?x), (have_image ?r ?o ?m), (communicated_soil_data ?x), (visible_from ?o ?x), (can_traverse ?r ?y ?x), (communicated_image_data ?o ?m), (can_traverse ?r ?x ?y), (visible_from ?o ?x), (visible_from ?o ?y), (equipped_for_imaging ?r), (at_rock_sample ?x), (at ?r ?y), (have_rock_analysis ?r ?x), (at_rock_sample ?y), (equipped_for_imaging ?r), (communicated_soil_data ?y), (at_rock_sample ?y), (have_soil_analysis ?r ?x), (have_image ?r ?o ?m), (have_rock_analysis ?r ?y), (at ?r ?x), (have_soil_analysis ?r ?x), (at_soil_sample ?y), (equipped_for_soil_analysis ?r), (visible ?y ?x), (at ?r ?x), (equipped_for_soil_analysis ?r), (visible ?x ?y), (communicated_rock_data ?y), (at_soil_sample ?x), (have_rock_analysis ?r ?x), (can_traverse ?r ?y ?x), (communicated_rock_data ?x), (at_rock_sample ?x), 
;; communicate_rock_data action has changed: (communicated_rock_data ?p), (at ?r ?y), (available ?r), (at_rock_sample ?p), (can_traverse ?r ?y ?x), (can_traverse ?r ?x ?y), (equipped_for_soil_analysis ?r), (have_soil_analysis ?r ?y), (communicated_soil_data ?x), (at_rock_sample ?y), (can_traverse ?r ?y ?p), (have_soil_analysis ?r ?y), (communicated_soil_data ?p), (at ?r ?p), (communicated_rock_data ?x), (at_lander ?l ?x), (at_soil_sample ?y), (have_soil_analysis ?r ?x), (visible ?y ?p), (at_rock_sample ?x), (visible ?x ?y), (visible ?y ?p), (have_rock_analysis ?r ?p), (communicated_rock_data ?y), (at_soil_sample ?p), (visible ?p ?y), (communicated_soil_data ?p), (channel_free ?l), (can_traverse ?r ?p ?x), (visible ?p ?y), (at ?r ?y), (can_traverse ?r ?p ?y), (equipped_for_rock_analysis ?r), (at_rock_sample ?p), (visible ?x ?p), (have_rock_analysis ?r ?x), (communicated_soil_data ?x), (at_rock_sample ?y), (can_traverse ?r ?x ?p), (at_lander ?l ?y), (equipped_for_imaging ?r), (at_rock_sample ?x), (visible ?p ?x), (equipped_for_imaging ?r), (have_soil_analysis ?r ?x), (visible ?x ?y), (have_rock_analysis ?r ?y), (can_traverse ?r ?x ?y), (can_traverse ?r ?p ?y), (channel_free ?l), (can_traverse ?r ?y ?p), (at_soil_sample ?y), (have_rock_analysis ?r ?x), (equipped_for_soil_analysis ?r), (communicated_soil_data ?y), (visible ?p ?x), (at ?r ?p), (have_soil_analysis ?r ?p), (communicated_soil_data ?y), (at ?r ?x), (can_traverse ?r ?x ?p), (at_lander ?l ?p), (available ?r), (visible ?y ?x), (visible ?x ?p), (communicated_rock_data ?x), (have_soil_analysis ?r ?p), (equipped_for_rock_analysis ?r), (can_traverse ?r ?p ?x), (at_soil_sample ?p), (at_lander ?l ?p), (at_soil_sample ?x), 
;; sample_rock action has changed: (full ?s), (at_soil_sample ?p), (equipped_for_soil_analysis ?x), (equipped_for_soil_analysis ?x), (communicated_soil_data ?p), (equipped_for_imaging ?x), (have_soil_analysis ?x ?p), (at ?x ?p), (full ?s), (communicated_soil_data ?p), (at_rock_sample ?p), (available ?x), (store_of ?s ?x), (at_rock_sample ?p), (at ?x ?p), (communicated_rock_data ?p), (empty ?s), (at_soil_sample ?p), (available ?x), (empty ?s), (have_soil_analysis ?x ?p), (have_rock_analysis ?x ?p), 
;; sample_soil action has changed: (at_rock_sample ?p), (communicated_soil_data ?p), (have_rock_analysis ?x ?p), (available ?x), (at ?x ?p), (communicated_rock_data ?p), (equipped_for_soil_analysis ?x), (store_of ?s ?x), (available ?x), (have_soil_analysis ?x ?p), (full ?s), (equipped_for_soil_analysis ?x), (empty ?s), (full ?s), (communicated_rock_data ?p), (have_rock_analysis ?x ?p), (at_rock_sample ?p), (have_soil_analysis ?x ?p), (at ?x ?p), (communicated_soil_data ?p), (equipped_for_rock_analysis ?x), (at_soil_sample ?p), (equipped_for_imaging ?x), (equipped_for_rock_analysis ?x), (empty ?s), 
;; Last_reduced_capability_num_dropped_pals: None

